# Generated by Django 2.0.6 on 2018-07-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180714_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_name', to='customer.Customer'),
        ),
    ]
