# Generated by Django 2.0.6 on 2018-06-12 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateField(verbose_name='creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('other_details', models.TextField()),
                ('create_date', models.DateField(verbose_name='creation date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Country')),
            ],
            options={
                'verbose_name_plural': 'customers',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('create_date', models.DateField(verbose_name='creation date')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Identification'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'surname'], name='customer_cu_first_n_f3f58d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id_number'], name='identity_idx'),
        ),
    ]
