# Generated by Django 2.0.6 on 2018-07-14 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='ZAR', max_length=8),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='customer.Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_type', to='customer.Identification'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Country'),
        ),
    ]
