# Generated by Django 2.0.6 on 2018-07-14 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180714_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='identification',
            options={'ordering': ['name'], 'verbose_name_plural': 'identifications'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
    ]
