# Generated by Django 2.0.6 on 2018-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180714_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
